### PR TITLE
Add rtg investigator

### PR DESCRIPTION
**Pull request by JasperO98**

### CODE REVIEW

**Comment by hexylena** [comment]
This tool won't work, I fear.

- there are no dependencies declared, so nothing will be installed automatically
- we have to figure out where to get the dependencies from, probably http://www.realtimegenomics.com/  but that's really messy
- none of these tools have been touched since 2012.

Is there an alternative tool suite we can use? Can you share a bit about the use case for this?

**Comment by JasperO98** [comment]
I would like to compare VCFs and get precision and recall metrics. Previously I had done this using hap.py locally, however that one is not available in the toolshed. Its no problem I can also compare the VCFs locally.

**Comment by hexylena** [comment]
hap.py is in bioconda, so we could wrap it up in a galaxy tool if it's helpful! If you have the command lines you want to run (just to know which options to focus on), we can start wrapping that and it'll be useful for everyone I reckon. And in the meantime, maybe run hap.py locally?

**Comment by hexylena** [comment]
Are you using hap.py with RTG? Or without, using xcmp?

**Comment by hexylena** [comment]
> This feature requires a version of rtg-tools which supports the GA4GH benchmarking intermediate file formats (see ga4gh/benchmarking-tools). Currently, such a version is available in this branch: realtimegenomics/rtg-tools@ga4gh-test

oh, probably not then

**Comment by JasperO98** [comment]
No I do not use it with RTG

**Comment by hexylena** [comment]
Actually would you be up for learning how to wrap tools? It's honestly not too bad. You write a single XML file which describes the command line, and we can put it in Galaxy. (And then you aren't stuck waiting on me, to construct nice pipelines)

- https://anaconda.org/bioconda/hap.py hap.py is in bioconda, so the really hard part is done
- https://bio.tools/hap.py it has a bio.tools ID which is useful
- All you'd have to do is try following this section of the tutorial to make the xml: https://training.galaxyproject.org/training-material/topics/dev/tutorials/tool-from-scratch/tutorial.html#galaxy-tool-wrappers
- the full documentation is all here for hap.py https://github.com/Illumina/hap.py/blob/master/doc/happy.md#full-list-of-command-line-options

Or we can ask around, maybe Dennis or someone else has interest in learning about the wrapping process?

**Comment by JasperO98** [comment]
No I'm up for it, that only makes it easier for you and me and I might need to add more tools in the future. Thanks for the useful links Im gonna have a look at it!

**Comment by JasperO98** [comment]
Happy is now available in the toolshed

**Pull request closed without merging**
