### PR TITLE
Add happy

### PR DESCRIPTION
**Pull request by JasperO98**

### CODE REVIEW

**Comment by hexylena** [comment]
It's...almost available. https://github.com/galaxyproject/tools-iuc/pull/4343#issuecomment-1021331613 will merge when it is.

**Comment by hexylena** [comment]
could you resovle the merge conflicts in the meantime?

**Comment by JasperO98** [comment]
Will do

**Comment by hexylena** [comment]
xref https://github.com/galaxyproject/tools-iuc/pull/4350

**Comment by JasperO98** [comment]
This PR can be merged now right?

**Comment by hexylena** [comment]
yep!

**Pull request merged**
